# Generated by Django 3.2.13 on 2022-06-10 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pochven", "0002_auto_20220610_2012"),
    ]

    operations = [
        migrations.AddField(
            model_name="solarsystem",
            name="home",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="solarsystem",
            name="order",
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
