version: '3.4'

services:

  pochvenscouts:
    image: pochvenscouts
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    environment:
      DEFAULT_DATABASE_DSN: psql://postgres:postgres@postgres:5432/postgres
    ports:
      - 8000:8000
    volumes:
      - .:/code/
      
  postgres:
    image: postgres:13-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres

  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - 1025:1025
      - 8025:8025
